ozone-his/ozone-e2e

.github/workflows/pro.yml, README.md, package.json
Ticket → [OZ-354](https://mekomsolutions.atlassian.net/browse/OZ-354?focusedCommentId=42989)
[OZ-354]: https://mekomsolutions.atlassian.net/browse/OZ-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-354: Refactored 'ozone-e2e-pro' → 'ozone-e2e' in README.

e2e/tests/testAnalyticsIntegration.spec.ts, e2e/utils/functions/testBase.ts
Ticket → [OZ-483](https://mekomsolutions.atlassian.net/browse/OZ-483)
[OZ-483]: https://mekomsolutions.atlassian.net/browse/OZ-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-483: Update Analytics tests to align with changes from flattening of queries

e2e/tests/testOdooIntegration.spec.ts, e2e/utils/functions/testBase.ts
Ticket → [OZ-401](https://mekomsolutions.atlassian.net/browse/OZ-401)
Description: This PR brings changes  adding E2E test verifying a patient with free dosage drug order gets synced as a customer in Odoo.
[OZ-401]: https://mekomsolutions.atlassian.net/browse/OZ-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-401: Patient with free text medication dosage becomes customer in Odoo

.github/workflows/ci.yml, package.json, yarn.lock
Ticket → [OZ-523](https://mekomsolutions.atlassian.net/browse/OZ-523)
[OZ-523]: https://mekomsolutions.atlassian.net/browse/OZ-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-523: Add GitHub Actions workflow to publish Ozone E2E tests

.github/workflows/ci.yml, package.json
Ticket [OZ-523](https://mekomsolutions.atlassian.net/browse/OZ-523)
This PR fixes the 400 Bad Request issue during authentication, logs at https://github.com/ozone-his/ozone-e2e/actions/runs/8478411141/job/23230694800
[OZ-523]: https://mekomsolutions.atlassian.net/browse/OZ-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-523: Appended '/' to the npm registry url.

package.json, yarn.lock
Ticket → [OZ-542](https://mekomsolutions.atlassian.net/browse/OZ-542)
[OZ-542]: https://mekomsolutions.atlassian.net/browse/OZ-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-542: Bumped playwright version to 1.43.0

.env, e2e/tests/testSupersetIntegration.spec.ts, e2e/utils/configs/globalSetup.ts, e2e/utils/functions/testBase.ts
Ticket → [OZ-548](https://mekomsolutions.atlassian.net/browse/OZ-548)
[OZ-548]: https://mekomsolutions.atlassian.net/browse/OZ-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-548: Added relevant self documenting comments to the .env file.

.env, e2e/tests/openmrs-senaite-flows.spec.ts, e2e/utils/functions/erpnext.ts, e2e/utils/functions/keycloak.ts, e2e/utils/functions/odoo.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/senaite.ts, e2e/utils/functions/superset.ts
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-589
This PR introduces changes to support developers to easily run E2E tests against the local instance.
=> OZ-589: E2E tests should run against local instance

.env, e2e/utils/functions/openmrs.ts
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-589
Refer to this convo: https://mekomsolutions.slack.com/archives/G421UNF5L/p1718277618645779?thread_ts=1718022016.604379&cid=G421UNF5L
=> OZ-589: Removed unneccessary authentication when running against local instance

e2e/tests/odoo-openmrs-flows.spec.ts, e2e/tests/openmrs-senaite-flows.spec.ts, e2e/utils/functions/openmrs.ts, package.json
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-635
=> OZ-635: E2E tests should use the order basket when ordering lab tests

.gitignore, e2e/tests/odoo-openmrs-flows.spec.ts
JIRA link: https://mekomsolutions.atlassian.net/browse/OZ-593
=> OZ-593: Updated E2E test for odoo-openmrs-flows

e2e/utils/functions/openmrs.ts
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-670
Description → This PR includes a change to fix the element locator for the 'Start visit' button, which comes from upstream.
=> OZ-670: Corrected element locator for 'Start visit' button

e2e/tests/erpnext-openmrs-flows.spec.ts, e2e/tests/keycloak-openmrs-flows.spec.ts, e2e/tests/keycloak-superset-flows.spec.ts, e2e/tests/odoo-openmrs-flows.spec.ts, e2e/tests/openmrs-senaite-flows.spec.ts, e2e/tests/openmrs-superset-flows.spec.ts, e2e/utils/functions/erpnext.ts, e2e/utils/functions/keycloak.ts, e2e/utils/functions/odoo.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/senaite.ts, e2e/utils/functions/superset.ts, package.json, yarn.lock
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-705
This PRs introduces changes that are;
-  Updating E2E tests for flows between OpenMRS and Superset
-  Upgrading Playwright version to 1.47
-  Improving E2E tests for all the Ozone flows.
=> OZ-705: Updated E2E test flows between OpenMRS and Superset + Upgraded Playwright version to 1.47.

e2e/tests/keycloak-odoo-flows.spec.ts, e2e/tests/keycloak-senaite-flows.spec.ts, e2e/tests/keycloak-superset-flows.spec.ts, e2e/tests/odoo-openmrs-flows.spec.ts, e2e/tests/odoo-superset-flows.spec.ts, e2e/tests/openmrs-senaite-flows.spec.ts, e2e/utils/functions/odoo.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/senaite.ts, e2e/utils/functions/superset.ts, package.json, playwright.config.ts, yarn.lock
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-725
=> OZ-725: E2E test verifying drug order with free text dosing instructions sync correctly in Odoo + upgraded Playwright to version 1.48.1

e2e/tests/keycloak-superset-flows.spec.ts, e2e/tests/openmrs-senaite-flows.spec.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/senaite.ts, package.json
JIRA: https://mekomsolutions.atlassian.net/browse/OZ-517
=> OZ-517: Fix extra button click to create partitions for SENAITE 2.5.0

e2e/tests/keycloak-odoo-flows.spec.ts, e2e/utils/functions/odoo.ts, package.json
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-707
=> OZ-707: Deleting a synced Odoo group deletes the corresponding Keycloak role.

e2e/tests/keycloak-openmrs-flows.spec.ts, e2e/tests/keycloak-superset-flows.spec.ts, e2e/tests/odoo-openmrs-flows.spec.ts, e2e/utils/functions/erpnext.ts, e2e/utils/functions/keycloak.ts, e2e/utils/functions/odoo.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/senaite.ts, e2e/utils/functions/superset.ts, package.json, yarn.lock
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-767
=> OZ-767: Upgraded Playwright version to 1.49.0

e2e/tests/erpnext-openmrs-flows.spec.ts, e2e/utils/functions/erpnext.ts, e2e/utils/functions/openmrs.ts, playwright.config.ts
This PR updated editing patient in the EMR and fixes test cases for the O3 → ERPNext flows.
=> Updated editing test patient + Fixed test cases for O3 → ERPNext flows.

e2e/tests/openmrs-superset-flows.spec.ts, e2e/utils/functions/keycloak.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/superset.ts, package.json
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-936
=> OZ-936: Superset should contain datasets per flattened table on a fresh instance.

e2e/tests/keycloak-odoo-flows.spec.ts, e2e/tests/odoo-openmrs-flows.spec.ts, e2e/tests/odoo-superset-flows.spec.ts, e2e/utils/functions/odoo.ts, package.json
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-949
This PR updates the E2E tests for Odoo flows following the upgrade from Odoo 14 to Odoo 17.
=> OZ-949: Update e2e tests for Odoo flows to run on Odoo 17

e2e/tests/erpnext-openmrs-flows.spec.ts, e2e/tests/keycloak-odoo-flows.spec.ts, e2e/tests/keycloak-openmrs-flows.spec.ts, e2e/tests/keycloak-senaite-flows.spec.ts, e2e/tests/keycloak-superset-flows.spec.ts, e2e/tests/odoo-openmrs-flows.spec.ts, e2e/tests/odoo-superset-flows.spec.ts, e2e/tests/openmrs-orthanc-flows.spec.ts, e2e/tests/openmrs-senaite-flows.spec.ts, e2e/tests/openmrs-superset-flows.spec.ts, e2e/utils/functions/erpnext.ts, e2e/utils/functions/keycloak.ts, e2e/utils/functions/odoo.ts, e2e/utils/functions/openmrs.ts, e2e/utils/functions/senaite.ts, e2e/utils/functions/superset.ts, package.json, playwright.config.ts, yarn.lock
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-934
=> OZ-934: Run e2e tests on non-admin user
