ozone-his/ozone-e2e

e2e/utils/functions/testBase.ts
package.json

This upgrades playwright to the latest version 1.42.1 (See release notes at https://playwright.dev/docs/release-notes) + Renaming 'User' to 'My account' as a change from upstream.

Upgraded playwright to 1.42.1 + Renamed 'User' to 'My Account'

---

e2e/tests/testAnalyticsIntegration.spec.ts
e2e/tests/testSenaiteIntegration.spec.ts
e2e/utils/functions/testBase.ts

Ticket → [OZ-336](https://mekomsolutions.atlassian.net/browse/OZ-336?focusedCommentId=41838)
[OZ-336]: https://mekomsolutions.atlassian.net/browse/OZ-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Description → This PR adds E2E test asserting that voiding an OpenMRS observation updates observations dataset in Superset

OZ-336: Voiding an OpenMRS observation updates observations dataset in Superset

---

.github/workflows/ci.yml
package.json

This PR addresses the failures occurring in GitHub Actions when publishing E2E tests to the NPM Registry.

 Remove 'publish' script from package.json

---

.github/workflows/ci.yml
package.json
yarn.lock

Ticket [OZ-523](https://mekomsolutions.atlassian.net/browse/OZ-523)
This PR adjusts Ozone E2E versioning in order  track the Ozone bleeding edge. As soon as when there is a release of Ozone, we release Ozone E2E version with the corresponding Ozone version.
Reference: https://mekomsolutions.slack.com/archives/G421UNF5L/p1712914368677929?thread_ts=1712911941.447549&cid=G421UNF5L
[OZ-523]: https://mekomsolutions.atlassian.net/browse/OZ-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-523: Use 'next' version to track the Ozone bleeding edge

---

e2e/tests/keycloak-openmrs-flows.spec.ts
e2e/tests/odoo-openmrs-flows.spec.ts
e2e/tests/openmrs-senaite-flows.spec.ts
e2e/tests/openmrs-superset-flows.spec.ts
e2e/utils/functions/keycloak.ts
e2e/utils/functions/odoo.ts
e2e/utils/functions/openmrs.ts
e2e/utils/functions/senaite.ts
e2e/utils/functions/superset.ts
package.json

Ticket [OZ-562](https://mekomsolutions.atlassian.net/browse/OZ-562)
[OZ-562]: https://mekomsolutions.atlassian.net/browse/OZ-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-562: Refactored component-specific user actions

---

e2e/tests/odoo-openmrs-flows.spec.ts
package.json

Ticket [OZ-553](https://mekomsolutions.atlassian.net/browse/OZ-553)
Description: This PR adds an E2E test for discontinuing a synced drug order of an Odoo customer with multiple quotation lines.
[OZ-553]: https://mekomsolutions.atlassian.net/browse/OZ-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-553: E2E test for discontinuation of synced drug order on Odoo quotation with multiple lines.

---

.env
e2e/tests/erpnext-openmrs-flows.spec.ts
e2e/tests/odoo-openmrs-flows.spec.ts
e2e/utils/configs/globalSetup.ts
e2e/utils/functions/erpnext.ts
e2e/utils/functions/openmrs.ts
package.json

Ticket [OZ-541](https://mekomsolutions.atlassian.net/browse/OZ-541)
This PR adds E2E tests for the flows between O3 and ERPNext;
- Ordering a lab test for an OpenMRS patient creates the corresponding ERPNext customer.
- Ordering a drug for an OpenMRS patient creates the corresponding ERPNext customer with a filled quotation.
- Ending an OpenMRS patient visit with a synced drug order updates the corresponding ERPNext draft quotation to an open state.
- Revising a synced OpenMRS drug order edits the corresponding ERPNext quotation line.
- Ordering a drug with a free text medication dosage for an OpenMRS patient creates the corresponding ERPNext customer with a filled quotation.
- Discontinuing a synced OpenMRS drug order for an ERPNext customer with a single quotation line removes the …

OZ-541: E2E tests for the flows between  O3 and ERPNext.

---

e2e/tests/odoo-openmrs-flows.spec.ts
e2e/tests/openmrs-senaite-flows.spec.ts
e2e/tests/openmrs-superset-flows.spec.ts
e2e/utils/functions/openmrs.ts
package.json

Ticket [OZ-554](https://mekomsolutions.atlassian.net/browse/OZ-554)
[OZ-554]: https://mekomsolutions.atlassian.net/browse/OZ-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR adds the following E2E tests handling voidable entities when streaming with Analytics.
- Voiding an OpenMRS patient updates the patient in Superset patients table.
- Voiding an OpenMRS condition updates the condition in Superset conditions table.
- Voiding an OpenMRS encounter updates the encounter in Superset encounters table.
- Cancelling an OpenMRS appointment updates the appointment in Superset appointments table.

OZ-554: E2E tests for handling voided entities when streaming with Analytics

---

e2e/tests/erpnext-openmrs-flows.spec.ts
package.json

This PR changes ERPNext tests to use voidPatient() instead of deletePatient(), updated in [OZ-554](https://mekomsolutions.atlassian.net/browse/OZ-554)
[OZ-554]: https://mekomsolutions.atlassian.net/browse/OZ-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-554: Renamed deletePatient() to voidPatient()

---

e2e/tests/keycloak-openmrs-flows.spec.ts
e2e/tests/keycloak-superset-flows.spec.ts
package.json
yarn.lock

Ticket → [OZ-590](https://mekomsolutions.atlassian.net/browse/OZ-590)
This PR refactors E2E test for Keycloak Superset flows into a separate file plus updating playwright  version to 1.44.1
[OZ-590]: https://mekomsolutions.atlassian.net/browse/OZ-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-590: Refactored E2E tests for Keycloak-Superset flows + Updated playwright to 1.44.1

---

e2e/tests/erpnext-openmrs-flows.spec.ts
e2e/tests/odoo-openmrs-flows.spec.ts
package.json

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-252
This PR adds E2E test verifying that discontinuing a synced OpenMRS lab order for an Odoo customer with a single quotation line cancels the corresponding quotation.

OZ-252: Discontinuing a synced lab order cancels corresponding quotation line in Odoo

---

.env
e2e/tests/erpnext-openmrs-flows.spec.ts
e2e/tests/odoo-openmrs-flows.spec.ts
e2e/utils/functions/openmrs.ts
package.json

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-541
This PR adds the following E2E tests for the flows between ERPNext and OpenMRS:
- Editing the details of an OpenMRS patient with a synced lab order edits the corresponding ERPNext customer details.
- Editing the details of an OpenMRS patient with a synced drug order edits the corresponding ERPNext customer details.
- Ordering a drug for an OpenMRS patient within a visit creates the corresponding ERPNext customer with a filled quotation linked to the visit.

OZ-541: E2E tests for flows between ERPNext and OpenMRS

---

package.json
yarn.lock

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-656
This PR upgrades playwright to the latest version 1.45.2. Release notes at https://playwright.dev/docs/release-notes

OZ-656: Upgraded Playwright version to 1.45.2

---

e2e/tests/odoo-openmrs-flows.spec.ts
e2e/tests/odoo-superset-flows.spec.ts
e2e/tests/openmrs-superset-flows.spec.ts
e2e/utils/functions/odoo.ts
e2e/utils/functions/openmrs.ts
package.json

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-345
This PR adds E2E tests for the Odoo and Superset integration. Here are the test cases:
- Creating an Odoo sale order line generates an entry in Superset\'s sale_order_lines table.
- A (synced) sale order line in Odoo generates an entry in Superset\'s sale_order_lines table.

OZ 345:  E2E tests verifying creating an Odoo sale order line generates an entry in Superset's sale_order_lines table.

---

e2e/tests/keycloak-odoo-flows.spec.ts
e2e/tests/keycloak-openmrs-flows.spec.ts
e2e/tests/keycloak-senaite-flows.spec.ts
e2e/tests/keycloak-superset-flows.spec.ts
e2e/utils/functions/keycloak.ts
e2e/utils/functions/odoo.ts
e2e/utils/functions/openmrs.ts
e2e/utils/functions/superset.ts
package.json
playwright.config.ts

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-707
This PR adds E2E tests for the flows between Keycloak and Odoo.
- Existing Odoo groups create the corresponding Keycloak role.
- Creating new group in Odoo creates the role in Keycloak.
- Renaming a group in Odoo updates the corresponding role in Keycloak.

OZ-707: E2E tests verifying Odoo groups are synced to Keycloak.

---

e2e/tests/odoo-openmrs-flows.spec.ts
e2e/utils/functions/openmrs.ts
package.json

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-525
This PR adds the following e2e tests:
- Ordering a lab test for an OpenMRS patient with weight creates the weight in the corresponding Odoo customer details.
- Recording a patient's weight in OpenMRS on the second order creates the weight in the corresponding Odoo customer details.

OZ-525: E2E test verifying that patient's weight is synced to Odoo

---

e2e/tests/odoo-openmrs-flows.spec.ts
e2e/utils/functions/openmrs.ts
package.json

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-763
This PR adds e2e test verifying:
- patient's date of birth is synced to Odoo upon making an order in O3
- editing patient's date of birth edits the corresponding Odoo customer details.

OZ-763: E2E test verifying that patient's date of birth is synced to Odoo

---

e2e/tests/keycloak-odoo-flows.spec.ts
e2e/tests/keycloak-openmrs-flows.spec.ts
e2e/tests/keycloak-senaite-flows.spec.ts
e2e/tests/odoo-superset-flows.spec.ts
e2e/tests/openmrs-superset-flows.spec.ts
e2e/utils/functions/odoo.ts
e2e/utils/functions/openmrs.ts
package.json
playwright.config.ts

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-711
This PR adds tests for Odoo → Analytics streaming and covers the following scenarios.
- Revising an Odoo sale order line modifies the corresponding entry in Superset's sale_order_lines table.
- Voiding an Odoo sale order line updates the corresponding entry in Superset's sale_order_lines table.
- Deleting an Odoo quotation line removes the corresponding entry in Superset's sale_order_lines table.

OZ-711: Modifying the details of a sale order in Odoo should update the respective entry in Superset's sale_order_lines table.

---

.env
.github/workflows/e2e.yml
.github/workflows/pro.yml
e2e/tests/openmrs-orthanc-flows.spec.ts
e2e/utils/configs/globalSetup.ts
e2e/utils/functions/openmrs.ts
e2e/utils/functions/orthanc.ts
playwright.config.ts

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-831
This PR adds e2e tests for the OpenMRS and Orthanc flows covering the following test case: 
- Uploading a DICOM study in Orthanc creates the corresponding radiology image for the OpenMRS patient.

OZ-831: Add e2e tests for Orthanc → OpenMRS flows + Remove `Cache dependencies` step for GA workflow.

---

.github/workflows/e2e.yml
package.json

This PR updates the script to use Bash's `$?` to capture the Playwright test command's exit code
and correctly sets the `jobStatusPretty` environment variable for the Slack message.
Previously, the job status was being checked using `${{ job.status }}` inside the `run` block,
which does not evaluate in shell context. This caused the `jobStatusPretty` variable to always
be empty in the Slack notification.

fix(ci): correctly set test status in Slack message by using shell exit code.
